---
tasks:
- name: init
  short: i
  script: bash scripts/githook.sh
  description: setup git hooks
  usage: setup git hooks
- name: coverage
  short: c
  description: test a package (fzf is required)
  usage: test a package (fzf is required)
  script: "bash scripts/coverage.sh {{.path}}"
  args:
  - name: path
- name: test
  short: t
  description: test
  usage: test
  script: go test ./... -covermode=atomic
  require:
    exec:
    - go
- name: fmt
  description: format the go code
  usage: format the go code
  script: bash scripts/fmt.sh
  require:
    exec:
    - bash
    - go
- name: vet
  short: v
  description: go vet
  usage: go vet
  script: go vet ./...
  require:
    exec:
    - go
- name: lint
  short: l
  description: lint the go code
  usage: lint the go code
  script: golangci-lint run
  require:
    exec:
    - golangci-lint
- name: release
  short: r
  description: release the new version
  usage: release the new version
  script: |
    git tag "{{.version}}"
    git push origin "{{.version}}"
  args:
  - name: version
    required: true
    validate:
    - regexp: "^v\\d+\\.\\d+.\\d+(-\\d+)?$"
- name: durl
  description: check dead links (durl is required)
  usage: check dead links (durl is required)
  script: bash scripts/durl.sh
  require:
    exec:
    - bash
    - durl
- name: ci-local
  description: run the Drone pipeline at localhost (drone-cli is required)
  usage: run the Drone pipeline at localhost (drone-cli is required)
  script: time drone exec --pipeline build --event pull_request
  environment:
    LOCAL: "true"
  require:
    exec:
    - drone
- name: shellcheck
  description: shellcheck
  usage: shellcheck
  script: shellcheck scripts/* githooks/*
  require:
    exec:
    - shellcheck
- name: shfmt
  description: shfmt
  usage: shfmt
  script: shfmt -l -w scripts/* githooks/*
  require:
    exec:
    - shfmt
- name: yamllint
  description: yamllint
  usage: yamllint
  script: 'find . \( -name "*.yml" -o -name "*.yaml" \) -print0 | xargs -0 yamllint -c .yamllint.yml'
  require:
    exec:
    - yamllint
- name: lambda-hello
  description: lambda hello
  type: lambda
  function_name: hello
  region: ap-northeast-1
  log_type: Tail
  # invocation_type: Event
  flags:
  - name: key1
    default: foo
  payload:
  - name: key1
    value: "{{.key1}}"
  - name: key2
    value: zoo
  - name: key3
    value: bar
