---
kind: pipeline
name: durl
clone:
  depth: 1
steps:
- name: durl
  image: quay.io/suzuki_shunsuke/durl:1.0.0
  commands:
  - sh scripts/durl.sh
---
kind: pipeline
name: shell scripts
clone:
  depth: 1
steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine:v0.7.2
  commands:
  - shellcheck scripts/* githooks/*
- name: shfmt
  image: mvdan/shfmt:v3.3.0-alpine
  commands:
  - shfmt -d .
---
kind: pipeline
name: yamllint
steps:
- name: yamllint
  image: quay.io/suzuki_shunsuke/yamllint:1.23.0
  commands:
  - 'find . \( -name "*.yml" -o -name "*.yaml" \) -print0 | xargs -0 yamllint -c .yamllint.yml'
---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
- name: gopath
  temp: {}
steps:
- name: download go modules
  image: golang:1.17.0
  commands:
  - go mod download
  volumes: &volumes
  - name: gopath
    path: /go
- name: golangci-lint
  image: golangci/golangci-lint:v1.30.0-alpine
  commands:
  - golangci-lint run
  volumes: *volumes
- name: test
  image: golang:1.17.0
  commands:
  - bash ci/test.sh
  environment:
    CC_TEST_REPORTER_ID:
      from_secret: cc_test_reporter_id
  volumes: *volumes
- name: remove changes
  image: &image_git plugins/git
  commands:
  # Sometimes it is failed to release by goreleaser due to changes of go.sum
  - git checkout -- .

- name: fetch tags to release
  image: *image_git
  commands:
  - git fetch --tags
  when:
    event:
    - tag
- name: release
  image: goreleaser/goreleaser:v0.177.0
  commands:
  - goreleaser release
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  volumes: *volumes
  when:
    event:
    - tag

- name: release (skip publish)
  image: goreleaser/goreleaser:v0.177.0
  commands:
  - goreleaser release --snapshot
  volumes: *volumes
  when:
    event:
    - pull_request
    - push
