---
linters:
  enable-all: true
  disable:
    - wsl
    - testpackage
    - godot
    - err113
    - lll
    - funlen
    - gocognit
    - godox
    - nestif
    - nlreturn
    - forbidigo
    - cyclop
    - paralleltest
    - tagliatelle
    - varnamelen
    - wrapcheck
    - gocritic
    - ireturn
    - exhaustruct
    - depguard
    - tagalign
    - exportloopref # WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
