---
linters:
  enable-all: true
  disable:
    - wsl
    - testpackage
    - godot
    - err113
    - lll
    - funlen
    - gocognit
    - godox
    - nestif
    - nlreturn
    - forbidigo
    - cyclop
    - paralleltest
    - tagliatelle
    - varnamelen
    - wrapcheck
    - gocritic
    - ireturn
    - exhaustruct
    - depguard
    - tagalign
    - tenv # WARN The linter 'tenv' is deprecated (since v1.64.0) due to: Duplicate feature another linter. Replaced by usetesting.
