---
linters:
  enable-all: true
  disable:
  - wsl
  - testpackage
  - godot
  - goerr113
  - lll
  - funlen
  - gocognit
  - godox
  - nestif
  - nlreturn
  - forbidigo
  - cyclop
  - exhaustivestruct
  - paralleltest
  - tagliatelle
  - varnamelen
  - wrapcheck
  - gocritic
  - ireturn
  - gomnd
