---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/imports/actionlint.yaml
      - aqua/imports/reviewdog.yaml
permissions: {}
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@67b3612237144931fa976f6ef10e257b4c601492 # v0.4.0
    with:
      aqua_version: v1.36.0
      aqua_policy_config: aqua/policy.yaml
    permissions:
      pull-requests: write
      contents: read
