---
name: test
on: pull_request
permissions: {}
jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@ebc738e18933219d457229048b81ee0d1bed6bdf # v3.0.0
    with:
      aqua_version: v2.45.0
    permissions:
      pull-requests: write
      contents: read # To checkout private repository

  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: go.mod
      - run: go install ./cmd/cmdx
      - run: cmdx help
